/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.zacharydhamilton.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Fruit extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -131020505061615982L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Fruit\",\"namespace\":\"com.github.zacharydhamilton.events\",\"fields\":[{\"name\":\"kind\",\"type\":\"string\",\"doc\":\"Kind of fruit\"},{\"name\":\"color\",\"type\":\"string\",\"doc\":\"Color of the fruit\"},{\"name\":\"organic\",\"type\":\"boolean\",\"doc\":\"Whether or not the fruit is organic\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Fruit> ENCODER =
      new BinaryMessageEncoder<Fruit>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Fruit> DECODER =
      new BinaryMessageDecoder<Fruit>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Fruit> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Fruit> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Fruit> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Fruit>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Fruit to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Fruit from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Fruit instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Fruit fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Kind of fruit */
  private java.lang.CharSequence kind;
  /** Color of the fruit */
  private java.lang.CharSequence color;
  /** Whether or not the fruit is organic */
  private boolean organic;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Fruit() {}

  /**
   * All-args constructor.
   * @param kind Kind of fruit
   * @param color Color of the fruit
   * @param organic Whether or not the fruit is organic
   */
  public Fruit(java.lang.CharSequence kind, java.lang.CharSequence color, java.lang.Boolean organic) {
    this.kind = kind;
    this.color = color;
    this.organic = organic;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return kind;
    case 1: return color;
    case 2: return organic;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: kind = (java.lang.CharSequence)value$; break;
    case 1: color = (java.lang.CharSequence)value$; break;
    case 2: organic = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'kind' field.
   * @return Kind of fruit
   */
  public java.lang.CharSequence getKind() {
    return kind;
  }


  /**
   * Sets the value of the 'kind' field.
   * Kind of fruit
   * @param value the value to set.
   */
  public void setKind(java.lang.CharSequence value) {
    this.kind = value;
  }

  /**
   * Gets the value of the 'color' field.
   * @return Color of the fruit
   */
  public java.lang.CharSequence getColor() {
    return color;
  }


  /**
   * Sets the value of the 'color' field.
   * Color of the fruit
   * @param value the value to set.
   */
  public void setColor(java.lang.CharSequence value) {
    this.color = value;
  }

  /**
   * Gets the value of the 'organic' field.
   * @return Whether or not the fruit is organic
   */
  public boolean getOrganic() {
    return organic;
  }


  /**
   * Sets the value of the 'organic' field.
   * Whether or not the fruit is organic
   * @param value the value to set.
   */
  public void setOrganic(boolean value) {
    this.organic = value;
  }

  /**
   * Creates a new Fruit RecordBuilder.
   * @return A new Fruit RecordBuilder
   */
  public static com.github.zacharydhamilton.events.Fruit.Builder newBuilder() {
    return new com.github.zacharydhamilton.events.Fruit.Builder();
  }

  /**
   * Creates a new Fruit RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Fruit RecordBuilder
   */
  public static com.github.zacharydhamilton.events.Fruit.Builder newBuilder(com.github.zacharydhamilton.events.Fruit.Builder other) {
    if (other == null) {
      return new com.github.zacharydhamilton.events.Fruit.Builder();
    } else {
      return new com.github.zacharydhamilton.events.Fruit.Builder(other);
    }
  }

  /**
   * Creates a new Fruit RecordBuilder by copying an existing Fruit instance.
   * @param other The existing instance to copy.
   * @return A new Fruit RecordBuilder
   */
  public static com.github.zacharydhamilton.events.Fruit.Builder newBuilder(com.github.zacharydhamilton.events.Fruit other) {
    if (other == null) {
      return new com.github.zacharydhamilton.events.Fruit.Builder();
    } else {
      return new com.github.zacharydhamilton.events.Fruit.Builder(other);
    }
  }

  /**
   * RecordBuilder for Fruit instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Fruit>
    implements org.apache.avro.data.RecordBuilder<Fruit> {

    /** Kind of fruit */
    private java.lang.CharSequence kind;
    /** Color of the fruit */
    private java.lang.CharSequence color;
    /** Whether or not the fruit is organic */
    private boolean organic;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.zacharydhamilton.events.Fruit.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.kind)) {
        this.kind = data().deepCopy(fields()[0].schema(), other.kind);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.color)) {
        this.color = data().deepCopy(fields()[1].schema(), other.color);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.organic)) {
        this.organic = data().deepCopy(fields()[2].schema(), other.organic);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Fruit instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.zacharydhamilton.events.Fruit other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.kind)) {
        this.kind = data().deepCopy(fields()[0].schema(), other.kind);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.color)) {
        this.color = data().deepCopy(fields()[1].schema(), other.color);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.organic)) {
        this.organic = data().deepCopy(fields()[2].schema(), other.organic);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'kind' field.
      * Kind of fruit
      * @return The value.
      */
    public java.lang.CharSequence getKind() {
      return kind;
    }


    /**
      * Sets the value of the 'kind' field.
      * Kind of fruit
      * @param value The value of 'kind'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Fruit.Builder setKind(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.kind = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'kind' field has been set.
      * Kind of fruit
      * @return True if the 'kind' field has been set, false otherwise.
      */
    public boolean hasKind() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'kind' field.
      * Kind of fruit
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Fruit.Builder clearKind() {
      kind = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'color' field.
      * Color of the fruit
      * @return The value.
      */
    public java.lang.CharSequence getColor() {
      return color;
    }


    /**
      * Sets the value of the 'color' field.
      * Color of the fruit
      * @param value The value of 'color'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Fruit.Builder setColor(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.color = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'color' field has been set.
      * Color of the fruit
      * @return True if the 'color' field has been set, false otherwise.
      */
    public boolean hasColor() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'color' field.
      * Color of the fruit
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Fruit.Builder clearColor() {
      color = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'organic' field.
      * Whether or not the fruit is organic
      * @return The value.
      */
    public boolean getOrganic() {
      return organic;
    }


    /**
      * Sets the value of the 'organic' field.
      * Whether or not the fruit is organic
      * @param value The value of 'organic'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Fruit.Builder setOrganic(boolean value) {
      validate(fields()[2], value);
      this.organic = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'organic' field has been set.
      * Whether or not the fruit is organic
      * @return True if the 'organic' field has been set, false otherwise.
      */
    public boolean hasOrganic() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'organic' field.
      * Whether or not the fruit is organic
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Fruit.Builder clearOrganic() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Fruit build() {
      try {
        Fruit record = new Fruit();
        record.kind = fieldSetFlags()[0] ? this.kind : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.color = fieldSetFlags()[1] ? this.color : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.organic = fieldSetFlags()[2] ? this.organic : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Fruit>
    WRITER$ = (org.apache.avro.io.DatumWriter<Fruit>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Fruit>
    READER$ = (org.apache.avro.io.DatumReader<Fruit>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.kind);

    out.writeString(this.color);

    out.writeBoolean(this.organic);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.kind = in.readString(this.kind instanceof Utf8 ? (Utf8)this.kind : null);

      this.color = in.readString(this.color instanceof Utf8 ? (Utf8)this.color : null);

      this.organic = in.readBoolean();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.kind = in.readString(this.kind instanceof Utf8 ? (Utf8)this.kind : null);
          break;

        case 1:
          this.color = in.readString(this.color instanceof Utf8 ? (Utf8)this.color : null);
          break;

        case 2:
          this.organic = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










