/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.zacharydhamilton.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Jelly extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2372660854615223439L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Jelly\",\"namespace\":\"com.github.zacharydhamilton.events\",\"fields\":[{\"name\":\"flavor\",\"type\":\"string\",\"doc\":\"The flavor of this Jelly (i.e. grape, strawberry, raspberry).\"},{\"name\":\"organic\",\"type\":\"boolean\",\"doc\":\"Is this organic or not.\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Jelly> ENCODER =
      new BinaryMessageEncoder<Jelly>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Jelly> DECODER =
      new BinaryMessageDecoder<Jelly>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Jelly> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Jelly> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Jelly> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Jelly>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Jelly to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Jelly from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Jelly instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Jelly fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The flavor of this Jelly (i.e. grape, strawberry, raspberry). */
  private java.lang.CharSequence flavor;
  /** Is this organic or not. */
  private boolean organic;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Jelly() {}

  /**
   * All-args constructor.
   * @param flavor The flavor of this Jelly (i.e. grape, strawberry, raspberry).
   * @param organic Is this organic or not.
   */
  public Jelly(java.lang.CharSequence flavor, java.lang.Boolean organic) {
    this.flavor = flavor;
    this.organic = organic;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return flavor;
    case 1: return organic;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: flavor = (java.lang.CharSequence)value$; break;
    case 1: organic = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'flavor' field.
   * @return The flavor of this Jelly (i.e. grape, strawberry, raspberry).
   */
  public java.lang.CharSequence getFlavor() {
    return flavor;
  }


  /**
   * Sets the value of the 'flavor' field.
   * The flavor of this Jelly (i.e. grape, strawberry, raspberry).
   * @param value the value to set.
   */
  public void setFlavor(java.lang.CharSequence value) {
    this.flavor = value;
  }

  /**
   * Gets the value of the 'organic' field.
   * @return Is this organic or not.
   */
  public boolean getOrganic() {
    return organic;
  }


  /**
   * Sets the value of the 'organic' field.
   * Is this organic or not.
   * @param value the value to set.
   */
  public void setOrganic(boolean value) {
    this.organic = value;
  }

  /**
   * Creates a new Jelly RecordBuilder.
   * @return A new Jelly RecordBuilder
   */
  public static com.github.zacharydhamilton.events.Jelly.Builder newBuilder() {
    return new com.github.zacharydhamilton.events.Jelly.Builder();
  }

  /**
   * Creates a new Jelly RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Jelly RecordBuilder
   */
  public static com.github.zacharydhamilton.events.Jelly.Builder newBuilder(com.github.zacharydhamilton.events.Jelly.Builder other) {
    if (other == null) {
      return new com.github.zacharydhamilton.events.Jelly.Builder();
    } else {
      return new com.github.zacharydhamilton.events.Jelly.Builder(other);
    }
  }

  /**
   * Creates a new Jelly RecordBuilder by copying an existing Jelly instance.
   * @param other The existing instance to copy.
   * @return A new Jelly RecordBuilder
   */
  public static com.github.zacharydhamilton.events.Jelly.Builder newBuilder(com.github.zacharydhamilton.events.Jelly other) {
    if (other == null) {
      return new com.github.zacharydhamilton.events.Jelly.Builder();
    } else {
      return new com.github.zacharydhamilton.events.Jelly.Builder(other);
    }
  }

  /**
   * RecordBuilder for Jelly instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Jelly>
    implements org.apache.avro.data.RecordBuilder<Jelly> {

    /** The flavor of this Jelly (i.e. grape, strawberry, raspberry). */
    private java.lang.CharSequence flavor;
    /** Is this organic or not. */
    private boolean organic;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.zacharydhamilton.events.Jelly.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.flavor)) {
        this.flavor = data().deepCopy(fields()[0].schema(), other.flavor);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.organic)) {
        this.organic = data().deepCopy(fields()[1].schema(), other.organic);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Jelly instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.zacharydhamilton.events.Jelly other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.flavor)) {
        this.flavor = data().deepCopy(fields()[0].schema(), other.flavor);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.organic)) {
        this.organic = data().deepCopy(fields()[1].schema(), other.organic);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'flavor' field.
      * The flavor of this Jelly (i.e. grape, strawberry, raspberry).
      * @return The value.
      */
    public java.lang.CharSequence getFlavor() {
      return flavor;
    }


    /**
      * Sets the value of the 'flavor' field.
      * The flavor of this Jelly (i.e. grape, strawberry, raspberry).
      * @param value The value of 'flavor'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Jelly.Builder setFlavor(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.flavor = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'flavor' field has been set.
      * The flavor of this Jelly (i.e. grape, strawberry, raspberry).
      * @return True if the 'flavor' field has been set, false otherwise.
      */
    public boolean hasFlavor() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'flavor' field.
      * The flavor of this Jelly (i.e. grape, strawberry, raspberry).
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Jelly.Builder clearFlavor() {
      flavor = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'organic' field.
      * Is this organic or not.
      * @return The value.
      */
    public boolean getOrganic() {
      return organic;
    }


    /**
      * Sets the value of the 'organic' field.
      * Is this organic or not.
      * @param value The value of 'organic'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Jelly.Builder setOrganic(boolean value) {
      validate(fields()[1], value);
      this.organic = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'organic' field has been set.
      * Is this organic or not.
      * @return True if the 'organic' field has been set, false otherwise.
      */
    public boolean hasOrganic() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'organic' field.
      * Is this organic or not.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.Jelly.Builder clearOrganic() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Jelly build() {
      try {
        Jelly record = new Jelly();
        record.flavor = fieldSetFlags()[0] ? this.flavor : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.organic = fieldSetFlags()[1] ? this.organic : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Jelly>
    WRITER$ = (org.apache.avro.io.DatumWriter<Jelly>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Jelly>
    READER$ = (org.apache.avro.io.DatumReader<Jelly>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.flavor);

    out.writeBoolean(this.organic);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.flavor = in.readString(this.flavor instanceof Utf8 ? (Utf8)this.flavor : null);

      this.organic = in.readBoolean();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.flavor = in.readString(this.flavor instanceof Utf8 ? (Utf8)this.flavor : null);
          break;

        case 1:
          this.organic = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










